"""Generate docs/DOCMAP.md — the index that is derived, never hand-maintained.

Output must be byte-identical across runs: sorted everywhere, and carrying no
date. A single "Generated on" line would make the freshness check permanently
red, which is how a generated index quietly becomes a hand-maintained one.

Three states are reported and never blurred: `stamped` (someone read this
against the code at a version), `unstamped` (nobody has), and `scaffolded`
(the tool wrote a skeleton and nothing more).
"""

import re
from pathlib import Path

from . import VERSION, findings as F
from .docs import AS_OF, SCAFFOLDED, STAMP, excluded, markdown_files

HEADER = "docs/DOCMAP.md"


def state_of(text):
    head = text[:800]
    if SCAFFOLDED.search(head):
        return "scaffolded"
    if STAMP.search(head):
        return "stamped"
    return "unstamped"


HTML_COMMENT = re.compile(r"<!--.*?-->", re.S)


def title_of(text, rel):
    """The document's own H1, with any HTML comment removed.

    A scaffolded file's heading is `# <!-- TODO(project-standard): … -->`.
    Copying that verbatim put an unresolved token inside a generated file whose
    own header says "do not edit by hand", and the token check then flagged it.
    """
    for line in (text or "").splitlines():
        if line.startswith("# "):
            title = HTML_COMMENT.sub("", line[2:]).strip()
            if title:
                return title
            break
    return Path(rel).stem.replace("_", " ").replace("-", " ")


def collect(ctx):
    rows = []
    for rel in sorted(markdown_files(ctx.tracked)):
        if rel == HEADER or excluded(rel):
            continue
        text = _read(ctx.repo, rel)
        stamp = STAMP.search(text[:800])
        asof = AS_OF.search(text[:800])
        rows.append({
            "path": rel,
            "title": title_of(text, rel),
            "state": state_of(text),
            "reviewed": stamp.group(1) if stamp else "",
            "as_of": asof.group(1) if asof else "",
        })
    return rows


def render(ctx):
    rows = collect(ctx)
    counts = {s: sum(1 for r in rows if r["state"] == s)
              for s in ("stamped", "unstamped", "scaffolded")}

    out = [
        "# Documentation map",
        "",
        f"**Generated by `project-standard {VERSION}` — do not edit by hand; "
        f"it is overwritten.**",
        "",
        f"`{len(rows)}` documents · "
        f"{counts['stamped']} stamped · {counts['unstamped']} unstamped · "
        f"{counts['scaffolded']} scaffolded",
        "",
        "A stamp means one thing: someone read this document against the code at",
        "that version. It is never applied in bulk, and a document nobody re-read",
        "stays `unstamped` rather than being filled in with something plausible.",
        "A `scaffolded` document is a skeleton the tool wrote; it asserts nothing.",
        "",
        "| Document | Title | State | Last reviewed | As of |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        out.append(
            f"| [`{r['path']}`]({_relative(r['path'])}) | {r['title']} | "
            f"{r['state']} | {r['reviewed'] or '—'} | "
            f"{('v' + r['as_of']) if r['as_of'] else '—'} |")
    out.append("")
    return "\n".join(out)


def check(ctx):
    """Check 3 — regenerate and diff. Any difference is a finding."""
    current = None
    path = Path(ctx.repo) / HEADER
    if HEADER in set(ctx.tracked) and path.is_file():
        current = path.read_text(errors="ignore")
    if current is None:
        return []
    if current.strip() != render(ctx).strip():
        return [F.error(
            "3", "DOCMAP is stale — regenerate with `project-standard generate`",
            path=HEADER)]
    return []


def _relative(path):
    return path[len("docs/"):] if path.startswith("docs/") else "../" + path


def _read(repo, rel):
    try:
        return (Path(repo) / rel).read_text(errors="ignore")
    except OSError:
        return ""
